spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/assignment
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234

  security:
    jwt:
      secret: "7JWI7JWM66Ck7KSY7JWI7JWM66Ck7KSY7JWI7JWM66Ck7KSY7JWI7JWM66Ck7KSY7JWI7JWM66Ck7KSY"
      expiration: 1800000


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDB53Dialect
    show-sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
